name: portfolio_opt
channels:
  - defaults
dependencies:
  - ipython==7.13.0
  - ipykernel==5.1.4
  - jupyter==1.0.0
  - numpy==1.19.2
  - pandas==1.1.3
  - pandas-datareader==0.9.0  
  - pip==20.0.2
  - seaborn==0.11.0
  - xlrd==1.2.0
  - pip:
    - cvxpy==1.1.7


